// <auto-generated />
namespace OnlineShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class orderDetail_Decimal_Change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderDetail_Decimal_Change));
        
        string IMigrationMetadata.Id
        {
            get { return "202009020934527_orderDetail_Decimal_Change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
